slurm:
    wall_time: "23:59:00"
    atoms_per_processor: 6
    max_processors: 20
    ram_per_processor: 2

lsf:
    wall_time: "03:59"
    atoms_per_processor: 6
    max_processors: 20
    ram_per_processor: 6

mongoDB:
    host: "127.0.0.1"
    port: 27017
    user: "autoqchem"
    password: "dftworks"